# Generated by Django 4.0.5 on 2022-09-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0003_remove_material_image5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(blank=True, choices=[('STANDARD', 'Standard'), ('STANDARD PLUS', 'StandardPlus'), ('SOLID DECORATIVE LAMINATE', 'SOLID DECORATIVE LAMINATE'), ('WORKTOPS', 'WORKTOPS'), ('WOOD WORKTOPS', 'WOOD WORKTOPS'), ('COMPACT LAMINATE WORKTOPS', 'COMPACT LAMINATE WORKTOPS'), ('SOLID ACRYLIC WORKTOPS', 'SOLID ACRYLIC WORKTOPS')], max_length=50, null=True),
        ),
    ]
