# Generated by Django 4.0.5 on 2022-09-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0004_alter_material_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='name',
        ),
        migrations.AddField(
            model_name='material',
            name='name_en',
            field=models.CharField(default='material', max_length=255),
        ),
        migrations.AddField(
            model_name='material',
            name='name_ge',
            field=models.CharField(default='მატერიალი', max_length=255),
        ),
    ]
