# Generated by Django 4.0.5 on 2022-08-31 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kitchen',
            old_name='note',
            new_name='note_en',
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image2',
            field=models.ImageField(default='media/default-product.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image3',
            field=models.ImageField(default='media/default-product.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image4',
            field=models.ImageField(default='media/default-product.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='image5',
            field=models.ImageField(default='media/default-product.jpeg', null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='kitchen',
            name='note_ge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='category',
            field=models.CharField(blank=True, choices=[('SINK', 'Sink'), ('MIXER', 'Mixer')], max_length=10, null=True),
        ),
    ]
