# Generated by Django 4.0.5 on 2022-08-31 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0002_rename_note_kitchen_note_en_kitchen_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitchen',
            name='image5',
        ),
    ]
