# Generated by Django 4.0.5 on 2022-10-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_remove_kitchen_name_kitchen_name_en_kitchen_name_ge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchen',
            name='category',
            field=models.CharField(blank=True, choices=[('SINKS', 'Sinks'), ('MIXERS', 'Mixers')], max_length=10, null=True),
        ),
    ]
